# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

def sharedPods
    pod 'Alamofire', '~> 4.0'
    pod 'Kingfisher', '~> 3.0'
    pod 'Unbox'
    pod 'SVProgressHUD'
end

def testingPods
    pod 'Quick'
    pod 'Nimble'
end

target 'Challenge' do
    sharedPods
end

target 'ChallengeTests' do
    sharedPods
    testingPods
end

target 'ChallengeUITests' do
    testingPods
end
